# File: trainforge/examples/mnist-basic/trainforge.yaml
# TrainForge configuration for MNIST training example

project:
  name: mnist-basic-example
  description: Simple MNIST classification with CNN

training:
  script: train.py
  requirements: requirements.txt

resources:
  gpu: 1
  cpu: 2
  memory: 4Gi

environment:
  python_version: "3.9"
  base_image: pytorch/pytorch:latest

# Optional: Training parameters
hyperparameters:
  batch_size: 128
  epochs: 5
  learning_rate: 0.01

# Optional: Experiment tracking
tracking:
  enabled: true
  metrics:
    - loss
    - accuracy
  artifacts:
    - best_model.pth
    - final_model.pth